require_relative '../node_modules/react-native-permissions/scripts/setup'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'mobile_app' do
  config = use_native_modules!

  pod 'GoogleUtilities', :modular_headers => true

  # react-native-permissions: faqat kerakli ruxsatlarni yoqish
  setup_permissions([
    'LocationAlways',
    'LocationWhenInUse',
  ])

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # Deployment target va Swift versiyasini belgilash
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        # Swift versiyasi qarama-qarshiligini hal qilish
        if config.build_settings['SWIFT_VERSION'].nil?
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
      end
    end
  end
end
